# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-28 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('phoneNumber', models.PositiveIntegerField()),
                ('emailAddress', models.EmailField(max_length=254)),
                ('streetAddress', models.TextField()),
                ('owner', models.CharField(max_length=30)),
            ],
        ),
    ]
